site_name: forgivenet suite
site_description: Developer onboarding for the forgivenet

# Project information
site_url: http://127.0.0.1:8000/
site_author: kailash-manasarovar
copyright: <a href="https://consensys.net">forgivenet®</a> © 2022


nav:
  - Home:
      - Welcome: index.md
  - Quick start local:
      - Pre-requisites: prerequisites.md
      - Compile and deploy: compile-deploy.md
      - Truffle console:
          - Set up and test: set-up-and-test.md
      - Remix:
          - Set up and test: set-up-and-test-remix.md
  - Goerli testnet:
      - Pre-requisites: goerli/prerequisites.md
      - Installation and set up: goerli/installation.md


theme:
  name: material
  custom_dir: custom_theme
  language: en
  logo: 'images/frgvn-symbol.png'
  favicon: 'images/favicon.ico'
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - search.suggest
    - search.highlight
    - search.share
    #- navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.indexes


extra:
  languages:
    en: English (en)
  debug: false
  version:
    number: latest
    switch: false
  logo_is_text: false
  support:
    company: forgivenet
  # analytics:
  #   provider:
  #   property:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/kailash-manasarovar
    - icon: material/web
      link: https://1frgvn.com



extra_css:
  - stylesheets/custom.css



markdown_extensions:
  - toc:
      permalink: true
      permalink_title: Link to this section
      toc_depth: 4
  - codehilite
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - markdown_include.include:
      base_path: developer-docs
  - admonition
  - footnotes
  - def_list
  - attr_list
  - abbr
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.keys
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - meta
  - smarty

plugins:
  search:
    lang: en
    separator: '[\s\-\.\_]+'
    prebuild_index: true
  #  git-revision-date-localized:
  #    locale: en
  markdownextradata: {}
#  minify:
#    minify_html: true
#    minify_js: true
#    htmlmin_opts:
#      remove_comments: true
# uncomment to exclude a folder in /developer-docs from final render.
# useful for include files
#  - exclude:
#      glob:
#        - cmd/*
#  mkdocs-video:
#    css_style:
#      weight: "50%"

